### ISSUE TITLE
Will not compile (GHC 6.12.3)

### ISSUE THREAD

**Issue by causal-agent** [bendmorris/scotch#1]
HEAD at the time of this writing (https://github.com/bendmorris/scotch/tree/7e71f3b9a7fd9c80637248056d78c1e2ce60327f) will not compile for me.
I installed the dependencies as listed on the Build Instructions wiki page then ran `ghc --make scotch -O2`. I get this error message:

```
Types.hs:19:7:
    Could not find module `Text.ParserCombinators.Parsec':
      Use -v to see a list of the files searched for.
```

I am running Arch Linux on x86_64, GHC version 6.12.3.

**Comment by bendmorris** [comment]
Try "cabal install parsec", and let me know if that solves the problem. If so, I'll update the build instructions.

**Comment by causal-agent** [comment]
That solved it, thanks.
