### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by duckinator** [bendmorris/scotch#2]
When attempting to install with cabal I got the following error:

```
Expressions.hs:60:7:
    Couldn't match expected type `Expr' against inferred type `Value'
      Expected type: ParsecT
                       String u Control.Monad.Identity.Identity Expr
      Inferred type: ParsecT
                       String u Control.Monad.Identity.Identity Value
    In the first argument of `try', namely `(reservedWord col)'
    In the first argument of `(<|>)', namely `try (reservedWord col)'
```

Full output at https://gist.github.com/09fbd39f189e8170d5ad

I've not worked with haskell for too long, and I've not even looked into Parsec yet, so I've got no clue where to start poking around.

(Current HEAD: https://github.com/bendmorris/scotch/tree/56afecf6acaf5b92eaab49cf79f1380afaa3f845)

**Comment by bendmorris** [comment]
Thanks for pointing that out. I think the latest push should have that fixed, so give it another try.

**Comment by duckinator** [comment]
Works!
