### ISSUE TITLE
Strong typing?

### ISSUE THREAD

**Issue by duckinator** [bendmorris/scotch#3]
I know this is a _feature_ request, not a issue/bug.

What I am wondering is, would you be willing to (eventually) look into adding a -strict command line flag or similar, to enable strict typing?

Or at least have it disable the ability to do something like `"foo" + 5` or `[1,2,3] + 4`?

Again, not asking for this any time soon - just curious if it will be taken under consideration.

EDIT: If there are no objections, I may look into this eventually. Want to get a good grip on both haskell and scotch before even trying something like this, though.

**Comment by bendmorris** [comment]
I'd certainly be willing to consider doing away with the weak typing, if it proves a better idea for the language. It would be pretty simple to implement; allowable operations (such as string + integer) are explicitly defined in Calc.hs and could simply be removed.

I'd like to think and discuss the pros and cons of strong vs. weak typing a bit more. Implicit conversion is in there for convenience and flexibility right now; strong typing would (arguably) catch more mistakes, although they would only be evident at runtime.

**Comment by duckinator** [comment]
Yea, both weak and strong typing have their benefits and pitfalls, it's all about which are found more worthwhile.

Do you have an IRC channel or similar, I'd be more than glad to stop by and spark some discussion ;)

**Comment by bendmorris** [comment]
Not yet. Scotch has mostly been promoted/discussed on Hacker News so far; I've just posted a thread asking for input there. Feel free to contribute your thoughts!

http://news.ycombinator.com/item?id=2204170

**Comment by duckinator** [comment]
Alright, will do. I'm "duckinator" on pretty much everything but github, by the way (just to avoid confusion).

**Comment by bendmorris** [comment]
I like the idea of an optional strict mode. I'll put that on the to do list.

**Comment by bendmorris** [comment]
Turned out to be a very simple feature to add. Strict mode is accessible now with -s or --strict.

**Comment by duckinator** [comment]
Awesome! I'll mess around with it in a bit and see if I can break it, but first I'm about to throw another bug report your way for something unrelated ;)

Does std.lib (idk what you prefer call it, i'm going off the errors i got while messing around earlier) work properly with -s/--strict?
And what particular operations does it change? Does it just not allow operations between different types, for things like math, concatenation, etc?

P.S.: that's a heck of a diff on the commit where you added -s
