### ISSUE TITLE
"Failed to import std.lib"

### ISSUE THREAD

**Issue by duckinator** [bendmorris/scotch#4]
If I run the REPL outside of scotch/scotch.lib, I get the following:

```
[~/dev/lang/scotch]$ scotch
Failed to import std.lib.

Exception in : Line 1, column 1
Undefined variable startup

>> 
```

It works flawlessly in scotch/scotch.lib:

```
[..ev/lang/scotch/scotch.lib]$ scotch
Scotch interpreter
0.3.0
For more information, type "about", "copyright" or "license".
>> 
```

Looks like just a case of relative to cwd vs relative to where the executable is.

**Comment by duckinator** [comment]
Also, I'm not sure how easily possible this would be with it being implemented in haskell, but:

Other languages I know of have `$FOO_DIST` and `$FOO_LIBS`

So you could have `$SCOTCH_DIST` be a path to the scotch repository (in my case, `~/dev/lang/scotch`, when ).

A nice, although unrelated, thing could be having `$SCOTCH_LIBS` be set to a directory with scotch libraries, laid out like the following:

```
$SCOTCH_LIBS/
    |
    |-- lib1
    |      |-- foo.sco
    |      `-- bar.sco
    `-- lib2
           |-- a.sco
           `-- b.sco
```

Just an idea. The first part will be far, far more useful in the short run :)

**Comment by bendmorris** [comment]
For now, the module search path will search the following locations:

(executable path)/scotch.lib/std/lib.sco
(cwd)/std/lib.sco

Adding the executable directory to your OS executable search path will allow you to use it from other directories without moving it, and the std modules will be accessible.

**Comment by duckinator** [comment]
Ahhh, ok. Issue was it copied the executable to ~/.bin when I installed it, but scotch.lib/ wasn't copied. ~/.zshenv ftw. I'm leaving this open in case you want to do this later/copy scotch.lib/something, close it if you want.

**Comment by duckinator** [comment]
Errrr, scratch that: I tried `PATH=$PATH:./scotch.lib scotch` and it does not run from in scotch/

EDIT: Sorry, done failing now. Fixed it with `ln -s $HOME/dev/lang/scotch/scotch.lib $HOME/.bin/` :)
